/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Enabling cheats on a Hardcore world is a compromise event
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.lan;

import com.truthsystems.TruthSystems;
import com.truthsystems.audit.CovenantVerifier;
import com.truthsystems.audit.ErrorLogger;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.server.ServerStartingEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.HashMap;
import java.util.Map;

/**
 * Detects runtime cheat flag activation on Hardcore worlds.
 *
 * <p>On {@link ServerStartingEvent}, the initial cheats state is captured.
 * Every 100 server ticks, the current state is compared to the last known
 * value. If cheats transition from disabled to enabled on a Hardcore world,
 * the world is marked {@link IntegrityFlag#LAN_CHEAT_DETECTED}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class CheatFlagWatcher {

    private static final Map<String, Boolean> lastCheatsStateByWorld = new HashMap<>();
    private static int tickCounter = 0;
    private static final int CHEAT_CHECK_INTERVAL_TICKS = 100;

    private CheatFlagWatcher() {}

    @SubscribeEvent
    public static void onServerStarting(ServerStartingEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        MinecraftServer server = event.getServer();
        if (!server.getWorldData().isHardcore()) return;
        String worldName = server.getWorldData().getLevelName();
        lastCheatsStateByWorld.put(worldName, server.getWorldData().getAllowCommands());
    }

    @SubscribeEvent
    public static void onServerTick(TickEvent.ServerTickEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (event.phase != TickEvent.Phase.END) return;

        tickCounter++;
        if (tickCounter < CHEAT_CHECK_INTERVAL_TICKS) return;
        tickCounter = 0;

        MinecraftServer server = event.getServer();
        if (server == null || !server.getWorldData().isHardcore()) return;
        if (!HikConfig.COMPROMISE_ON_LAN_CHEATS.get()) return;

        String worldName = server.getWorldData().getLevelName();
        boolean lastCheatsState = lastCheatsStateByWorld.getOrDefault(worldName, false);
        boolean currentCheatsState = server.getWorldData().getAllowCommands();
        if (!lastCheatsState && currentCheatsState) {
            DeathSealManager.markCompromised(worldName, IntegrityFlag.LAN_CHEAT_DETECTED);
        }
        if (!CovenantVerifier.verifyLanCheatBlocked(server)) {
            ErrorLogger.logError(
                    ErrorLogger.ErrorType.LAN_CHEAT_VIOLATION,
                    TruthSystems.MODID,
                    "lan_cheat_verification_failed",
                    "",
                    "");
        }
        lastCheatsStateByWorld.put(worldName, currentCheatsState);
    }
}
