/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Enabling cheats on a Hardcore world is a compromise event
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.lan;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.server.MinecraftServer;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.server.ServerStartingEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

/**
 * Detects runtime cheat flag activation on Hardcore worlds.
 *
 * <p>On {@link ServerStartingEvent}, the initial cheats state is captured.
 * Every 100 server ticks, the current state is compared to the last known
 * value. If cheats transition from disabled to enabled on a Hardcore world,
 * the world is marked {@link IntegrityFlag#LAN_CHEAT_DETECTED}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class CheatFlagWatcher {

    private static boolean lastCheatsState = false;
    private static int tickCounter = 0;

    private CheatFlagWatcher() {}

    @SubscribeEvent
    public static void onServerStarting(ServerStartingEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        MinecraftServer server = event.getServer();
        if (!server.getWorldData().isHardcore()) return;
        lastCheatsState = server.getWorldData().getAllowCommands();
    }

    @SubscribeEvent
    public static void onServerTick(TickEvent.ServerTickEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (event.phase != TickEvent.Phase.END) return;

        tickCounter++;
        if (tickCounter < 100) return;
        tickCounter = 0;

        MinecraftServer server = event.getServer();
        if (server == null || !server.getWorldData().isHardcore()) return;
        if (!HikConfig.COMPROMISE_ON_LAN_CHEATS.get()) return;

        boolean currentCheatsState = server.getWorldData().getAllowCommands();
        if (!lastCheatsState && currentCheatsState) {
            String worldName = server.getWorldData().getLevelName();
            DeathSealManager.markCompromised(worldName, IntegrityFlag.LAN_CHEAT_DETECTED);
        }
        lastCheatsState = currentCheatsState;
    }
}
