/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: LAN cheats must be disabled on Hardcore worlds to preserve integrity
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.lan;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.AbstractWidget;
import net.minecraft.client.gui.screens.ShareToLanScreen;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;
import com.truthsystems.hardcore.HikConfig;

/**
 * Mixin to disable the LAN "Allow Cheats" option on Hardcore worlds.
 * Uses @Inject rather than @Overwrite to be compatible with other mods.
 *
 * TODO (Phase 2): Also intercept the button click to show a warning message
 * explaining that cheats cannot be enabled on Hardcore worlds.
 */
@Mixin(ShareToLanScreen.class)
public class LanMenuMixin {

    @Inject(method = "init", at = @At("RETURN"))
    private void onInit(CallbackInfo ci) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        Minecraft mc = Minecraft.getInstance();
        if (mc.level == null || !mc.level.getLevelData().isHardcore()) return;

        ShareToLanScreen self = (ShareToLanScreen) (Object) this;
        self.children().stream()
                .filter(w -> w instanceof AbstractWidget)
                .map(w -> (AbstractWidget) w)
                .filter(btn -> {
                    String msg = btn.getMessage().getString().toLowerCase();
                    // Require both keywords to avoid disabling unrelated buttons
                    return msg.contains("cheat") || (msg.contains("allow") && msg.contains("cheat"));
                })
                .forEach(btn -> btn.active = false);
    }
}
