/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Truth-Only)
 * CONSTRAINT: A compromised world must become read-only to prevent further corruption
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.lan;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.Level;
import net.minecraftforge.event.level.BlockEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

/**
 * Enforces read-only mode on Hardcore worlds whose integrity is not
 * {@link IntegrityFlag#CLEAN}.
 *
 * <p>Block-break and block-place events are cancelled when
 * {@link HikConfig#READ_ONLY_ON_EXTERNAL_CHEAT_FLAG} is enabled and the
 * world integrity flag is anything other than {@code CLEAN}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class ReadOnlyWorldEnforcer {

    private ReadOnlyWorldEnforcer() {}

    @SubscribeEvent
    public static void onBlockBreak(BlockEvent.BreakEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (!HikConfig.READ_ONLY_ON_EXTERNAL_CHEAT_FLAG.get()) return;

        Level level = (Level) event.getLevel();
        if (!level.getLevelData().isHardcore()) return;
        if (!(level instanceof ServerLevel serverLevel)) return;

        String worldName = serverLevel.getServer().getWorldData().getLevelName();
        IntegrityFlag flag = DeathSealManager.getWorldIntegrity(worldName);
        if (flag != IntegrityFlag.CLEAN) {
            event.setCanceled(true);
        }
    }

    @SubscribeEvent
    public static void onBlockPlace(BlockEvent.EntityPlaceEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (!HikConfig.READ_ONLY_ON_EXTERNAL_CHEAT_FLAG.get()) return;

        Level level = (Level) event.getLevel();
        if (!level.getLevelData().isHardcore()) return;
        if (!(level instanceof ServerLevel serverLevel)) return;

        String worldName = serverLevel.getServer().getWorldData().getLevelName();
        IntegrityFlag flag = DeathSealManager.getWorldIntegrity(worldName);
        if (flag != IntegrityFlag.CLEAN) {
            event.setCanceled(true);
        }
    }
}
