/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Bijective World Inverter
 * PRINCIPLE: LOGOS (Truth-Only)
 * CONSTRAINT: swap(swap(x,y)) = identity (bijective verification)
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.inverter;

import net.minecraft.world.level.Level;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.entity.Entity;
import net.minecraft.nbt.CompoundTag;

public final class InversionLogic {

    public static void swap(Level level, BlockPos a, BlockPos b) {
        BlockState sa = level.getBlockState(a);
        BlockState sb = level.getBlockState(b);

        level.setBlock(a, sb, 3);
        level.setBlock(b, sa, 3);
    }
    
    public static void swapWithEntities(Level level, BlockPos a, BlockPos b) {
        // Swap block states
        swap(level, a, b);
        
        // Swap entities within 1 block radius
        var entitiesA = level.getEntitiesOfClass(Entity.class, 
            new net.minecraft.world.phys.AABB(a).inflate(1.0));
        var entitiesB = level.getEntitiesOfClass(Entity.class,
            new net.minecraft.world.phys.AABB(b).inflate(1.0));
        
        for (Entity e : entitiesA) {
            if (!entitiesB.contains(e)) {
                var offset = e.position().subtract(a.getX(), a.getY(), a.getZ());
                e.teleportTo(b.getX() + offset.x, b.getY() + offset.y, b.getZ() + offset.z);
            }
        }
        
        for (Entity e : entitiesB) {
            if (!entitiesA.contains(e)) {
                var offset = e.position().subtract(b.getX(), b.getY(), b.getZ());
                e.teleportTo(a.getX() + offset.x, a.getY() + offset.y, a.getZ() + offset.z);
            }
        }
    }

    public static boolean bijectiveCheck(Level level, BlockPos a, BlockPos b) {
        BlockState beforeA = level.getBlockState(a);
        BlockState beforeB = level.getBlockState(b);
        swap(level, a, b);
        swap(level, a, b);
        return level.getBlockState(a).equals(beforeA)
            && level.getBlockState(b).equals(beforeB);
    }
}
