/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Bijective World Inverter Block
 * PRINCIPLE: LOGOS (Bijective Operations)
 * CONSTRAINT: Right-click two positions to swap
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.inverter;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.core.BlockPos;

public class InverterBlock extends Block {
    
    public InverterBlock(BlockBehaviour.Properties properties) {
        super(properties);
    }

    @Override
    public InteractionResult use(BlockState state, Level level, BlockPos pos, 
                                  Player player, InteractionHand hand, BlockHitResult hit) {
        if (level.isClientSide) return InteractionResult.SUCCESS;
        
        // TODO: Store first position, then swap on second click
        // player.displayClientMessage(Component.literal("Inverter: Select second position"), true);
        
        return InteractionResult.SUCCESS;
    }
}
