/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Tractable Truth-Checking)
 * CONSTRAINT: All HIK behaviour governed by user-visible config keys
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore;

import net.minecraftforge.common.ForgeConfigSpec;

public class HikConfig {

    public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static final ForgeConfigSpec SPEC;

    public static final ForgeConfigSpec.BooleanValue ENABLE_HIK;
    public static final ForgeConfigSpec.ConfigValue<String> ARCHIVE_PATH;
    public static final ForgeConfigSpec.IntValue SPECTATOR_GRACE_MINUTES;
    public static final ForgeConfigSpec.IntValue VERIFICATION_API_PORT;
    public static final ForgeConfigSpec.BooleanValue ALLOW_SEALED_BACKUPS;
    public static final ForgeConfigSpec.BooleanValue STRICT_INVENTORY_PROVENANCE;
    public static final ForgeConfigSpec.BooleanValue COMPROMISE_ON_LAN_CHEATS;
    public static final ForgeConfigSpec.BooleanValue READ_ONLY_ON_EXTERNAL_CHEAT_FLAG;

    static {
        BUILDER.comment("Hardcore Integrity Keeper (HIK)").push("hardcore");

        ENABLE_HIK = BUILDER
                .comment("Master switch: enable the Hardcore Integrity Keeper subsystem.")
                .define("enable_hik", true);

        ARCHIVE_PATH = BUILDER
                .comment("Directory used for archived hardcore world saves.")
                .define("archive_path", "saves/archived");

        SPECTATOR_GRACE_MINUTES = BUILDER
                .comment("Minutes a dead player remains in spectator before their world is archived.")
                .defineInRange("spectator_grace_minutes", 10, 0, Integer.MAX_VALUE);

        VERIFICATION_API_PORT = BUILDER
                .comment("Port for the optional HTTP verification API. 0 = disabled.")
                .defineInRange("verification_api_port", 0, 0, 65535);

        ALLOW_SEALED_BACKUPS = BUILDER
                .comment("Allow server-side backups even after a death seal is active.")
                .define("allow_sealed_backups", true);

        STRICT_INVENTORY_PROVENANCE = BUILDER
                .comment("Track and verify full inventory provenance (Phase 2 feature, currently no-op).")
                .define("strict_inventory_provenance", false);

        COMPROMISE_ON_LAN_CHEATS = BUILDER
                .comment("Mark world as COMPROMISED when LAN cheats are enabled on a Hardcore world.")
                .define("compromise_on_lan_cheats", true);

        READ_ONLY_ON_EXTERNAL_CHEAT_FLAG = BUILDER
                .comment("Block all block-break/place events when world integrity is not CLEAN.")
                .define("read_only_on_external_cheat_flag", true);

        BUILDER.pop();
        SPEC = BUILDER.build();
    }

    private HikConfig() {}

    /**
     * Explicit initialization hook used by the mod entrypoint.
     * Forge loads the spec through {@code ModLoadingContext}; this method keeps
     * HIK startup explicit and testable.
     */
    public static void load() {
        // no-op; spec registration is handled in TruthSystems
    }
}
