/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Demonic Debugger
 * PRINCIPLE: KENOSIS (Self-Emptying Diagnostics)
 * CONSTRAINT: metrics correspond to actual server state
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.debugger;

import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;

public final class DebugMetrics {

    public static String lagReport(MinecraftServer server) {
        long chunkCount = 0;
        for (ServerLevel level : server.getAllLevels()) {
            chunkCount += level.getChunkSource().getLoadedChunksCount();
        }
        return "TPS=" + server.getAverageTickTime()
            + " | Chunks=" + chunkCount;
    }
}
