/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Demonic Debugger
 * PRINCIPLE: KENOSIS (Self-Emptying Diagnostics)
 * CONSTRAINT: metrics correspond to actual server state
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.debugger;

import net.minecraft.server.MinecraftServer;

public final class DebugMetrics {

    public static String lagReport(MinecraftServer server) {
        return "TPS=" + server.getAverageTickTime()
            + " | Chunks=" + server.getAllLevels().size();
    }
}
