/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Merkle Notary
 * PRINCIPLE: LOGOS (Cryptographic Verification)
 * CONSTRAINT: hash(chunk) = SHA-256(block_states)
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.merkle;

import net.minecraft.world.level.chunk.LevelChunk;
import net.minecraft.world.level.block.state.BlockState;

import java.security.MessageDigest;

public final class ChunkHasher {

    public static String hashChunk(LevelChunk chunk) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            chunk.getBlockEntitiesPos().forEach(pos -> {
                BlockState state = chunk.getBlockState(pos);
                md.update(state.toString().getBytes());
            });
            return bytesToHex(md.digest());
        } catch (Exception e) {
            return "ERROR";
        }
    }

    private static String bytesToHex(byte[] b) {
        StringBuilder sb = new StringBuilder();
        for (byte x : b) sb.append(String.format("%02x", x));
        return sb.toString();
    }
}
