/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Merkle Notary Block
 * PRINCIPLE: LOGOS (Visual Cryptographic Verification)
 * CONSTRAINT: Block displays real-time SHA-256 hash of chunk
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.merkle;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.EntityBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.Level;

public class NotaryBlock extends Block implements EntityBlock {
    
    public NotaryBlock(BlockBehaviour.Properties properties) {
        super(properties);
    }

    @Override
    public BlockEntity newBlockEntity(BlockPos pos, BlockState state) {
        return new NotaryBlockEntity(pos, state);
    }
}
