/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Merkle Notary Block Entity
 * PRINCIPLE: LOGOS (Real-time Hash Display)
 * CONSTRAINT: Updates hash every tick, displays as floating text
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.merkle;

import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.Level;
import net.minecraft.nbt.CompoundTag;

public class NotaryBlockEntity extends BlockEntity {
    
    private String currentHash = "";
    private int tickCounter = 0;
    
    public NotaryBlockEntity(BlockPos pos, BlockState state) {
        super(null, pos, state); // TODO: Register block entity type
    }

    public static void tick(Level level, BlockPos pos, BlockState state, NotaryBlockEntity entity) {
        if (level.isClientSide) return;
        
        entity.tickCounter++;
        
        // Update hash every 20 ticks (1 second)
        if (entity.tickCounter % 20 == 0) {
            var chunk = level.getChunkAt(pos);
            entity.currentHash = ChunkHasher.hashChunk(chunk);
            entity.setChanged();
        }
    }

    public String getCurrentHash() {
        return currentHash;
    }

    @Override
    protected void saveAdditional(CompoundTag tag) {
        super.saveAdditional(tag);
        tag.putString("ChunkHash", currentHash);
        tag.putInt("TickCounter", tickCounter);
    }

    @Override
    public void load(CompoundTag tag) {
        super.load(tag);
        currentHash = tag.getString("ChunkHash");
        tickCounter = tag.getInt("TickCounter");
    }
}
