/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * AUTHORITY: Jesus Christ (External, Immutable)
 * PRINCIPLES: LOGOS, CHALCEDON, GRACE, KENOSIS, AGAPE
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.ModLoadingContext;
import com.truthsystems.registry.*;

@Mod(TruthSystems.MODID)
public class TruthSystems {
    public static final String MODID = "truthsystems";

    @SuppressWarnings("removal")
    public TruthSystems(FMLJavaModLoadingContext context) {
        IEventBus bus = context.getModEventBus();
        ModBlocks.REGISTER.register(bus);
        ModItems.REGISTER.register(bus);
        ModBlockEntities.REGISTER.register(bus);
        ModEntities.REGISTER.register(bus);

        // Register HIK configuration
        ModLoadingContext.get().registerConfig(
            net.minecraftforge.fml.config.ModConfig.Type.COMMON,
            com.truthsystems.hardcore.HikConfig.SPEC,
            "truthsystems-hik.toml"
        );
    }
}
