/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Cryptographic Verification)
 * CONSTRAINT: Death records are immutable once sealed and checksum-protected
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.soulbind;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.nio.charset.StandardCharsets;

/**
 * Immutable record of a player's death in a Hardcore world.
 * The {@code checksum} field is a SHA-256 digest of the key fields,
 * allowing tamper detection after the entry is persisted.
 */
public class DeathLogEntry {

    private String playerUuid;
    private String playerName;
    private String worldName;
    private long deathTimestamp;
    private String deathCause;
    private String sessionId;
    private String checksum;
    private boolean locked;

    /** Default constructor required by Gson. */
    public DeathLogEntry() {}

    public DeathLogEntry(String playerUuid, String playerName, String worldName,
                         long deathTimestamp, String deathCause,
                         String sessionId, String checksum, boolean locked) {
        this.playerUuid = playerUuid;
        this.playerName = playerName;
        this.worldName = worldName;
        this.deathTimestamp = deathTimestamp;
        this.deathCause = deathCause;
        this.sessionId = sessionId;
        this.checksum = checksum;
        this.locked = locked;
    }

    // ---- Getters ----------------------------------------------------------------

    public String getPlayerUuid() { return playerUuid; }
    public String getPlayerName() { return playerName; }
    public String getWorldName() { return worldName; }
    public long getDeathTimestamp() { return deathTimestamp; }
    public String getDeathCause() { return deathCause; }
    public String getSessionId() { return sessionId; }
    public String getChecksum() { return checksum; }
    public boolean isLocked() { return locked; }

    // ---- Setters ----------------------------------------------------------------

    public void setPlayerUuid(String playerUuid) { this.playerUuid = playerUuid; }
    public void setPlayerName(String playerName) { this.playerName = playerName; }
    public void setWorldName(String worldName) { this.worldName = worldName; }
    public void setDeathTimestamp(long deathTimestamp) { this.deathTimestamp = deathTimestamp; }
    public void setDeathCause(String deathCause) { this.deathCause = deathCause; }
    public void setSessionId(String sessionId) { this.sessionId = sessionId; }
    public void setChecksum(String checksum) { this.checksum = checksum; }
    public void setLocked(boolean locked) { this.locked = locked; }

    // ---- Checksum ---------------------------------------------------------------

    /**
     * Computes SHA-256 of the key fields and stores it in {@code checksum}.
     * Fields: playerUuid | playerName | worldName | deathTimestamp | deathCause | sessionId | locked
     */
    public void computeChecksum() {
        this.checksum = computeChecksumValue();
    }

    /**
     * Returns {@code true} if the stored checksum matches a freshly computed one.
     */
    public boolean verifyChecksum() {
        if (this.checksum == null || this.checksum.isEmpty()) return false;
        return this.checksum.equals(computeChecksumValue());
    }

    private String computeChecksumValue() {
        String raw = playerUuid + "|" + playerName + "|" + worldName + "|"
                + deathTimestamp + "|" + deathCause + "|" + sessionId + "|" + locked;
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(raw.getBytes(StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder();
            for (byte b : hashBytes) {
                hex.append(String.format("%02x", b));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is always available on Java 17
            return "CHECKSUM_ERROR";
        }
    }
}
