/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Cryptographic Verification)
 * CONSTRAINT: Death seals persist across restarts; checksum mismatch triggers COMPROMISED
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.soulbind;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.truthsystems.audit.ErrorLogger;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

/**
 * Persists and retrieves {@link DeathLogEntry} files for Hardcore worlds.
 *
 * <p>Files are stored at {@code <worldDir>/soulbind/<uuid>.json}.
 * An in-memory {@link IntegrityFlag} map is maintained per world name.
 */
public class DeathSealManager {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Map<String, IntegrityFlag> worldIntegrityMap = new HashMap<>();

    private DeathSealManager() {}

    // ---- Persistence ------------------------------------------------------------

    /**
     * Writes a death log entry to {@code <worldDir>/soulbind/<uuid>.json}.
     */
    public static void sealDeath(Path worldDir, DeathLogEntry entry) {
        Path soulbindDir = worldDir.resolve("soulbind");
        try {
            Files.createDirectories(soulbindDir);
            Path entryFile = soulbindDir.resolve(entry.getPlayerUuid() + ".json");
            try (Writer writer = Files.newBufferedWriter(entryFile)) {
                GSON.toJson(entry, writer);
            }
        } catch (IOException e) {
            ErrorLogger.logError(ErrorLogger.ErrorType.MERKLE_MISMATCH,
                    "HIK/DeathSealManager", "sealDeath_io_error", "", "");
            System.err.println("[HIK] Failed to seal death for " + entry.getPlayerUuid() + ": " + e.getMessage());
        }
    }

    /**
     * Loads a death log entry for the given UUID.
     *
     * @return the entry, or {@code null} if not found. Marks world as
     *         {@link IntegrityFlag#TAMPERED_DEATH_LOG} if checksum fails.
     */
    public static DeathLogEntry loadSeal(Path worldDir, String uuid) {
        Path entryFile = worldDir.resolve("soulbind").resolve(uuid + ".json");
        if (!Files.exists(entryFile)) return null;
        try (Reader reader = Files.newBufferedReader(entryFile)) {
            DeathLogEntry entry = GSON.fromJson(reader, DeathLogEntry.class);
            if (entry == null) return null;
            if (!entry.verifyChecksum()) {
                String worldName = worldDir.getFileName() != null
                        ? worldDir.getFileName().toString() : "unknown";
                markCompromised(worldName, IntegrityFlag.TAMPERED_DEATH_LOG);
                return entry;
            }
            return entry;
        } catch (IOException e) {
            System.err.println("[HIK] Failed to load seal for " + uuid + ": " + e.getMessage());
            return null;
        }
    }

    /**
     * Returns {@code true} if the player has a valid, locked death seal.
     */
    public static boolean isSealed(Path worldDir, String uuid) {
        DeathLogEntry entry = loadSeal(worldDir, uuid);
        return entry != null && entry.isLocked();
    }

    // ---- Integrity map ----------------------------------------------------------

    /**
     * Returns the current integrity flag for the named world.
     * Defaults to {@link IntegrityFlag#UNKNOWN} if not set.
     */
    public static IntegrityFlag getWorldIntegrity(String worldName) {
        return worldIntegrityMap.getOrDefault(worldName, IntegrityFlag.UNKNOWN);
    }

    /** Explicitly sets the integrity flag for a world. */
    public static void setWorldIntegrity(String worldName, IntegrityFlag flag) {
        worldIntegrityMap.put(worldName, flag);
    }

    /**
     * Sets the integrity flag to the given reason and logs the event via
     * {@link ErrorLogger}.
     */
    public static void markCompromised(String worldName, IntegrityFlag reason) {
        worldIntegrityMap.put(worldName, reason);
        ErrorLogger.logError(ErrorLogger.ErrorType.MERKLE_MISMATCH,
                "HIK/DeathSealManager", reason.name(), "", "");
        System.err.println("[HIK] World '" + worldName + "' marked " + reason.name());
    }
}
