/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Every integrity state must be explicitly named and non-ambiguous
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.soulbind;

/**
 * Represents the integrity state of a Hardcore world as tracked by HIK.
 */
public enum IntegrityFlag {
    CLEAN,
    COMPROMISED,
    TAMPERED_DEATH_LOG,
    TAMPERED_LEVEL_DAT,
    ROLLBACK_DETECTED,
    LAN_CHEAT_DETECTED,
    UNKNOWN
}
