/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: Death in Hardcore is permanent; the seal must be enforced at every login
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.soulbind;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.backup.SessionIdManager;
import net.minecraft.network.chat.Component;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.storage.LevelResource;
import net.minecraftforge.event.entity.living.LivingDeathEvent;
import net.minecraftforge.event.entity.player.PlayerEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.nio.file.Path;

/**
 * Forge event handler that creates death seals on Hardcore death and
 * enforces spectator mode on login for sealed players.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class SoulbindEventHandler {

    @SubscribeEvent
    public static void onLivingDeath(LivingDeathEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (!(event.getEntity() instanceof ServerPlayer player)) return;

        ServerLevel level = (ServerLevel) player.level();
        if (!level.getLevelData().isHardcore()) return;

        MinecraftServer server = level.getServer();
        Path worldDir = server.getWorldPath(LevelResource.ROOT).toAbsolutePath();
        String uuid = player.getStringUUID();
        String name = player.getName().getString();
        String worldName = server.getWorldData().getLevelName();
        String cause = event.getSource().getLocalizedDeathMessage(player).getString();
        String sessionId = SessionIdManager.getOrCreateSessionId(worldDir, worldName);

        DeathLogEntry entry = DeathLogEntry.createSealed(
                uuid, name, worldName,
                System.currentTimeMillis(), cause, sessionId);

        DeathSealManager.sealDeath(worldDir, entry);
        DeathSealManager.setWorldIntegrity(worldName, IntegrityFlag.CLEAN);

        player.setGameMode(GameType.SPECTATOR);
    }

    @SubscribeEvent
    public static void onPlayerLogin(PlayerEvent.PlayerLoggedInEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (!(event.getEntity() instanceof ServerPlayer player)) return;

        ServerLevel level = (ServerLevel) player.serverLevel();
        if (!level.getLevelData().isHardcore()) return;

        MinecraftServer server = player.getServer();
        if (server == null) return;

        Path worldDir = server.getWorldPath(LevelResource.ROOT).toAbsolutePath();
        String uuid = player.getStringUUID();

        if (DeathSealManager.isSealed(worldDir, uuid)) {
            player.setGameMode(GameType.SPECTATOR);
            player.displayClientMessage(
                    Component.literal("[HIK] Your death is sealed. You are in spectator mode."), false);
        }
    }
}
