/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Rollback of game time must be detected and flagged immediately
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.backup;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.storage.LevelResource;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

/**
 * Detects obvious rollback/restore signals by persisting the last-seen game
 * tick to {@code <worldDir>/hik_continuity.json} every 600 ticks (≈30 s).
 *
 * <p>If the current tick is less than the persisted tick on the next write, a
 * rollback is inferred and the world is marked
 * {@link IntegrityFlag#ROLLBACK_DETECTED}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class BackupDetector {

    private static final String CONTINUITY_FILE = "hik_continuity.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Map<String, Long> lastTickMap = new HashMap<>();

    private BackupDetector() {}

    // ---- Forge event handler ----------------------------------------------------

    @SubscribeEvent
    public static void onLevelTick(TickEvent.LevelTickEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (event.phase != TickEvent.Phase.END) return;
        if (!(event.level instanceof ServerLevel serverLevel)) return;
        if (!serverLevel.getLevelData().isHardcore()) return;

        long gameTick = serverLevel.getGameTime();
        if (gameTick % 600 != 0) return;

        MinecraftServer server = serverLevel.getServer();
        Path worldDir = server.getWorldPath(LevelResource.ROOT).toAbsolutePath();
        String worldName = server.getWorldData().getLevelName();
        onWorldTick(worldDir, worldName, gameTick);
    }

    // ---- Public API -------------------------------------------------------------

    /**
     * Saves the current game tick to the continuity file and updates the in-memory map.
     */
    public static void recordTick(Path worldDir, String worldName, long currentTick) {
        lastTickMap.put(worldName, currentTick);
        Path continuityFile = worldDir.resolve(CONTINUITY_FILE);
        JsonObject obj = new JsonObject();
        obj.addProperty("last_tick", currentTick);
        obj.addProperty("world_name", worldName);
        try (Writer writer = Files.newBufferedWriter(continuityFile)) {
            GSON.toJson(obj, writer);
        } catch (IOException e) {
            System.err.println("[HIK] Failed to record tick: " + e.getMessage());
        }
    }

    /**
     * Returns {@code true} if the given tick is earlier than the persisted value,
     * indicating a rollback.
     */
    public static boolean detectRollback(Path worldDir, String worldName, long currentTick) {
        Long inMemory = lastTickMap.get(worldName);
        if (inMemory != null && currentTick < inMemory) return true;

        // Also check persisted value
        long persisted = loadPersistedTick(worldDir);
        if (persisted > 0 && currentTick < persisted) return true;

        return false;
    }

    /**
     * Called every 600 ticks. Checks for rollback; if detected, marks world
     * compromised. Then records the current tick.
     */
    public static void onWorldTick(Path worldDir, String worldName, long gameTick) {
        if (detectRollback(worldDir, worldName, gameTick)) {
            DeathSealManager.markCompromised(worldName, IntegrityFlag.ROLLBACK_DETECTED);
        }
        recordTick(worldDir, worldName, gameTick);
    }

    // ---- Helpers ----------------------------------------------------------------

    private static long loadPersistedTick(Path worldDir) {
        Path continuityFile = worldDir.resolve(CONTINUITY_FILE);
        if (!Files.exists(continuityFile)) return -1;
        try (Reader reader = Files.newBufferedReader(continuityFile)) {
            JsonObject obj = GSON.fromJson(reader, JsonObject.class);
            if (obj == null || !obj.has("last_tick")) return -1;
            return obj.get("last_tick").getAsLong();
        } catch (IOException e) {
            System.err.println("[HIK] Failed to load persisted tick: " + e.getMessage());
            return -1;
        }
    }
}
