/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Session IDs provide causal continuity across restarts
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.backup;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Manages per-world session IDs.
 *
 * <p>A session ID is a stable UUID generated when a world is first seen by HIK.
 * It is persisted to {@code <worldDir>/hik_session.json} and cached in memory.
 */
public class SessionIdManager {

    private static final String SESSION_FILE = "hik_session.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Map<String, String> sessionCache = new HashMap<>();

    private SessionIdManager() {}

    /**
     * Returns the cached session ID for {@code worldName}.
     * If absent, attempts to load it from disk; if still absent, generates a new
     * UUID, persists it, and caches it.
     */
    public static String getOrCreateSessionId(Path worldDir, String worldName) {
        String cached = sessionCache.get(worldName);
        if (cached != null) return cached;

        String loaded = loadSessionId(worldDir);
        if (loaded != null) {
            sessionCache.put(worldName, loaded);
            return loaded;
        }

        String newId = UUID.randomUUID().toString();
        persistSessionId(worldDir, newId, System.currentTimeMillis());
        sessionCache.put(worldName, newId);
        return newId;
    }

    /**
     * Writes the session data to {@code <worldDir>/hik_session.json}.
     */
    public static void persistSessionId(Path worldDir, String sessionId, long createdAt) {
        Path sessionFile = worldDir.resolve(SESSION_FILE);
        JsonObject obj = new JsonObject();
        obj.addProperty("session_id", sessionId);
        obj.addProperty("created_at", createdAt);
        // Determine world name from directory name if available
        String worldName = worldDir.getFileName() != null ? worldDir.getFileName().toString() : "unknown";
        obj.addProperty("world_name", worldName);
        try (Writer writer = Files.newBufferedWriter(sessionFile)) {
            GSON.toJson(obj, writer);
        } catch (IOException e) {
            System.err.println("[HIK] Failed to persist session ID: " + e.getMessage());
        }
    }

    /**
     * Reads the session ID from {@code <worldDir>/hik_session.json}.
     *
     * @return the session ID string, or {@code null} if absent or malformed.
     */
    public static String loadSessionId(Path worldDir) {
        Path sessionFile = worldDir.resolve(SESSION_FILE);
        if (!Files.exists(sessionFile)) return null;
        try (Reader reader = Files.newBufferedReader(sessionFile)) {
            JsonObject obj = GSON.fromJson(reader, JsonObject.class);
            if (obj == null || !obj.has("session_id")) return null;
            return obj.get("session_id").getAsString();
        } catch (IOException e) {
            System.err.println("[HIK] Failed to load session ID: " + e.getMessage());
            return null;
        }
    }
}
