/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Client-side HUD must reflect world integrity state in real time
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.integrity;

import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.RenderGuiOverlayEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import com.truthsystems.TruthSystems;

/**
 * Client-side HUD overlay that shows the current world integrity state.
 *
 * <p>Rendered in the top-left corner:
 * <ul>
 *   <li>GREEN "HIK: CLEAN" when integrity is {@link IntegrityFlag#CLEAN}
 *   <li>RED "HIK: &lt;FLAG&gt;" for any other state
 * </ul>
 * Not rendered when HIK is disabled or the current world is not Hardcore.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE, value = Dist.CLIENT)
public class IntegrityOverlay {

    @SubscribeEvent
    public static void onRenderOverlay(RenderGuiOverlayEvent.Post event) {
        if (!HikConfig.ENABLE_HIK.get()) return;

        Minecraft mc = Minecraft.getInstance();
        if (mc.level == null || !mc.level.getLevelData().isHardcore()) return;

        String worldName = "unknown";
        if (mc.getSingleplayerServer() != null) {
            worldName = mc.getSingleplayerServer().getWorldData().getLevelName();
        }
        // In multiplayer, the server-side world name is not directly accessible from
        // the client; the overlay will show UNKNOWN integrity in that case, which is
        // the correct safe default (server-side HIK checks still operate normally).

        IntegrityFlag flag = DeathSealManager.getWorldIntegrity(worldName);

        String label;
        int color;
        if (flag == IntegrityFlag.CLEAN) {
            label = "HIK: CLEAN";
            color = 0x55FF55;
        } else {
            label = "HIK: " + flag.name();
            color = 0xFF5555;
        }

        GuiGraphics graphics = event.getGuiGraphics();
        graphics.drawString(mc.font, label, 2, 2, color);
    }
}
