/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Cryptographic Verification)
 * CONSTRAINT: Tampering with level.dat must be detected on every world load
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.integrity;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.storage.LevelResource;
import net.minecraftforge.event.server.ServerStartingEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

/**
 * Watches level.dat for changes by storing the last-seen hash in memory and
 * comparing on demand.
 *
 * <p>On server start, delegates to {@link WorldChecksumValidator#initOrValidate}.
 * Periodic tamper-checks are triggered by callers (e.g., {@link
 * com.truthsystems.hardcore.backup.BackupDetector}).
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class LevelDatWatcher {

    private static final Map<String, String> lastKnownHashes = new HashMap<>();

    private LevelDatWatcher() {}

    // ---- Event handler ----------------------------------------------------------

    @SubscribeEvent
    public static void onServerStarting(ServerStartingEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;

        MinecraftServer server = event.getServer();
        if (!server.getWorldData().isHardcore()) return;

        Path worldDir = server.getWorldPath(LevelResource.ROOT).toAbsolutePath();
        String worldName = server.getWorldData().getLevelName();
        onWorldLoad(worldDir, worldName);
    }

    // ---- Public API -------------------------------------------------------------

    /**
     * Computes the current level.dat hash and delegates to
     * {@link WorldChecksumValidator#initOrValidate} for persisted comparison.
     */
    public static void onWorldLoad(Path worldDir, String worldName) {
        String hash = WorldChecksumValidator.computeLevelDatHash(worldDir);
        if (hash != null) {
            lastKnownHashes.put(worldName, hash);
        }
        WorldChecksumValidator.initOrValidate(worldDir, worldName);
    }

    /**
     * Computes the current hash and compares it to the last known value.
     * If they differ, marks the world as {@link IntegrityFlag#TAMPERED_LEVEL_DAT}.
     */
    public static void checkForTampering(Path worldDir, String worldName) {
        String currentHash = WorldChecksumValidator.computeLevelDatHash(worldDir);
        if (currentHash == null) return;

        String lastHash = lastKnownHashes.get(worldName);
        if (lastHash != null && !lastHash.equals(currentHash)) {
            DeathSealManager.markCompromised(worldName, IntegrityFlag.TAMPERED_LEVEL_DAT);
        }
        lastKnownHashes.put(worldName, currentHash);
    }
}
