/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: LOGOS (Cryptographic Verification)
 * CONSTRAINT: level.dat checksum must match persisted value; mismatch = TAMPERED
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.integrity;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;
import com.truthsystems.hardcore.soulbind.DeathSealManager;
import com.truthsystems.hardcore.soulbind.IntegrityFlag;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * Computes and validates SHA-256 checksums of key world files.
 *
 * <p>The checksum is stored in {@code <worldDir>/hik_integrity.json}.
 */
public class WorldChecksumValidator {

    private static final String CHECKSUM_FILE = "hik_integrity.json";
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private WorldChecksumValidator() {}

    /**
     * On world load: compute level.dat hash. If a stored hash exists, compare it.
     * If mismatched, mark world as {@link IntegrityFlag#TAMPERED_LEVEL_DAT};
     * otherwise persist the fresh hash.
     */
    public static void initOrValidate(Path worldDir, String worldName) {
        String currentHash = computeLevelDatHash(worldDir);
        if (currentHash == null) return;

        String persistedHash = loadPersistedChecksum(worldDir);
        if (persistedHash == null) {
            // First run – persist baseline
            persistChecksum(worldDir, currentHash);
            DeathSealManager.setWorldIntegrity(worldName, IntegrityFlag.CLEAN);
        } else if (!persistedHash.equals(currentHash)) {
            DeathSealManager.markCompromised(worldName, IntegrityFlag.TAMPERED_LEVEL_DAT);
        } else {
            DeathSealManager.setWorldIntegrity(worldName, IntegrityFlag.CLEAN);
        }
    }

    /**
     * Returns the SHA-256 hex digest of {@code <worldDir>/level.dat}, or
     * {@code null} if the file cannot be read.
     */
    public static String computeLevelDatHash(Path worldDir) {
        Path levelDat = worldDir.resolve("level.dat");
        if (!Files.exists(levelDat)) return null;
        try {
            byte[] bytes = Files.readAllBytes(levelDat);
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(bytes);
            StringBuilder hex = new StringBuilder();
            for (byte b : hashBytes) {
                hex.append(String.format("%02x", b));
            }
            return hex.toString();
        } catch (IOException | NoSuchAlgorithmException e) {
            System.err.println("[HIK] Failed to hash level.dat: " + e.getMessage());
            return null;
        }
    }

    /**
     * Writes {@code {"level_dat_hash": "<hash>"}} to
     * {@code <worldDir>/hik_integrity.json}.
     */
    public static void persistChecksum(Path worldDir, String hash) {
        Path checksumFile = worldDir.resolve(CHECKSUM_FILE);
        JsonObject obj = new JsonObject();
        obj.addProperty("level_dat_hash", hash);
        try (Writer writer = Files.newBufferedWriter(checksumFile)) {
            GSON.toJson(obj, writer);
        } catch (IOException e) {
            System.err.println("[HIK] Failed to persist checksum: " + e.getMessage());
        }
    }

    /**
     * Reads and returns the persisted hash, or {@code null} if the file is absent
     * or malformed.
     */
    public static String loadPersistedChecksum(Path worldDir) {
        Path checksumFile = worldDir.resolve(CHECKSUM_FILE);
        if (!Files.exists(checksumFile)) return null;
        try (Reader reader = Files.newBufferedReader(checksumFile)) {
            JsonObject obj = GSON.fromJson(reader, JsonObject.class);
            if (obj == null || !obj.has("level_dat_hash")) return null;
            return obj.get("level_dat_hash").getAsString();
        } catch (IOException e) {
            System.err.println("[HIK] Failed to load persisted checksum: " + e.getMessage());
            return null;
        }
    }

    /**
     * Returns {@code true} if the current level.dat hash matches the persisted one.
     * Marks the world as compromised on mismatch.
     */
    public static boolean validateChecksum(Path worldDir, String worldName) {
        String current = computeLevelDatHash(worldDir);
        if (current == null) return false;
        String persisted = loadPersistedChecksum(worldDir);
        if (persisted == null) {
            persistChecksum(worldDir, current);
            return true;
        }
        if (!persisted.equals(current)) {
            DeathSealManager.markCompromised(worldName, IntegrityFlag.TAMPERED_LEVEL_DAT);
            return false;
        }
        return true;
    }
}
