/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Causality Detector
 * PRINCIPLE: CHALCEDON (Divine Order, No Paradoxes)
 * CONSTRAINT: hasCycle() = false (acyclic causality)
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.causality;

import net.minecraft.core.BlockPos;
import java.util.*;

public final class RedstoneGraph {

    private final Map<BlockPos, Set<BlockPos>> edges = new HashMap<>();

    public void link(BlockPos a, BlockPos b) {
        edges.computeIfAbsent(a, k -> new HashSet<>()).add(b);
    }

    public boolean hasCycle() {
        Set<BlockPos> visited = new HashSet<>();
        Set<BlockPos> stack = new HashSet<>();

        for (BlockPos node : edges.keySet())
            if (dfs(node, visited, stack)) return true;

        return false;
    }

    private boolean dfs(BlockPos n, Set<BlockPos> v, Set<BlockPos> s) {
        if (s.contains(n)) return true;
        if (!v.add(n)) return false;
        s.add(n);
        for (BlockPos m : edges.getOrDefault(n, Set.of()))
            if (dfs(m, v, s)) return true;
        s.remove(n);
        return false;
    }
}
