/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Error-to-Truth Pipeline - Blacklist Manager
 * PRINCIPLE: CHALCEDON (Divine Order - Covenant-Ordered Deletion)
 * CONSTRAINT: Quarantine mods that violate covenant repeatedly
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.audit;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BlacklistManager {
    
    private static final Path BLACKLIST_FILE = Paths.get("blacklist_manifest.json");
    private static final Path QUARANTINE_DIR = Paths.get("mods", "quarantine");
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    
    static {
        try {
            Files.createDirectories(QUARANTINE_DIR);
        } catch (IOException e) {
            System.err.println("Failed to create quarantine directory: " + e.getMessage());
        }
    }
    
    public static void quarantineMod(String modName, String modHash, 
                                      List<String> failedErrors, 
                                      String lastValidStateHash) {
        
        List<Map<String, Object>> blacklist = loadBlacklist();
        
        Map<String, Object> entry = new HashMap<>();
        entry.put("mod", modName);
        entry.put("hash", modHash);
        entry.put("failed_errors", failedErrors);
        entry.put("quarantine_date", LocalDate.now().toString());
        entry.put("last_valid_state_hash", lastValidStateHash);
        entry.put("covenant_status", "VIOLATED");
        
        blacklist.add(entry);
        saveBlacklist(blacklist);
        
        System.out.println("[QUARANTINE] Mod quarantined: " + modName);
        System.out.println("[QUARANTINE] Hash: " + modHash);
        System.out.println("[QUARANTINE] Failed errors: " + failedErrors);
    }
    
    public static boolean isBlacklisted(String modHash) {
        List<Map<String, Object>> blacklist = loadBlacklist();
        for (Map<String, Object> entry : blacklist) {
            if (modHash.equals(entry.get("hash"))) {
                return true;
            }
        }
        return false;
    }
    
    private static List<Map<String, Object>> loadBlacklist() {
        if (!Files.exists(BLACKLIST_FILE)) {
            return new ArrayList<>();
        }
        
        try (FileReader reader = new FileReader(BLACKLIST_FILE.toFile())) {
            Type listType = new TypeToken<ArrayList<Map<String, Object>>>(){}.getType();
            return GSON.fromJson(reader, listType);
        } catch (IOException e) {
            System.err.println("Failed to load blacklist: " + e.getMessage());
            return new ArrayList<>();
        }
    }
    
    private static void saveBlacklist(List<Map<String, Object>> blacklist) {
        try (FileWriter writer = new FileWriter(BLACKLIST_FILE.toFile())) {
            GSON.toJson(blacklist, writer);
        } catch (IOException e) {
            System.err.println("Failed to save blacklist: " + e.getMessage());
        }
    }
}
