/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Error-to-Truth Pipeline - Covenant Compliance Interface
 * PRINCIPLE: AGAPE (Mod Self-Repair Capability)
 * CONSTRAINT: Mods must implement to enable PATH A (Self-Repair)
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.audit;

/**
 * Interface for mods that want to self-repair under covenant compliance.
 * 
 * Implements PATH A of the Error-to-Truth Pipeline:
 * - Mod receives error report
 * - Runs selfRepair() function
 * - Must pass all three verification tests
 * - If passes → unfrozen and continues
 * - If fails → escalates to PATH B (External Patch)
 */
public interface CovenantCompliant {
    
    /**
     * Attempt to repair the error.
     * 
     * @param errorId The unique error ID from ErrorLogger
     * @param failingCheck The specific check that failed
     * @return true if repair was successful, false otherwise
     */
    boolean selfRepair(String errorId, String failingCheck);
    
    /**
     * Verify that the mod's operations are bijective (invertible).
     * 
     * Test: swap(swap(x,y)) == identity
     * 
     * @return true if bijective property holds
     */
    boolean passBijectiveTest();
    
    /**
     * Verify that the mod doesn't corrupt chunk hashes.
     * 
     * Test: hash(chunk_after) == hash(chunk_before) OR explicitly updated
     * 
     * @return true if Merkle verification passes
     */
    boolean passMerkleVerification();
    
    /**
     * Verify that the mod doesn't create dependency loops.
     * 
     * Test: hasCycle(dependency_graph) == false
     * 
     * @return true if no causality loops detected
     */
    boolean passCausalCheck();
}
