/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Error-to-Truth Pipeline - Error Logger
 * PRINCIPLE: LOGOS (Forensic Autopsy, No Interpretation)
 * CONSTRAINT: Every error captured as hashed artifact
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.audit;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class ErrorLogger {
    
    private static final Path AUDIT_DIR = Paths.get("audit_logs");
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    
    public enum ErrorType {
        BIJECTIVE_VIOLATION,
        MERKLE_MISMATCH,
        CAUSALITY_LOOP,
        DEBUGGER_ALERT
    }
    
    static {
        try {
            Files.createDirectories(AUDIT_DIR);
        } catch (IOException e) {
            System.err.println("Failed to create audit directory: " + e.getMessage());
        }
    }
    
    public static String logError(ErrorType type, String violatingMod, 
                                   String failingCheck, String preStateHash, 
                                   String postStateHash) {
        
        String errorId = generateErrorId(type);
        
        Map<String, Object> auditEntry = new HashMap<>();
        auditEntry.put("error_id", errorId);
        auditEntry.put("timestamp", Instant.now().toString());
        auditEntry.put("violating_mod", violatingMod);
        auditEntry.put("error_type", type.name());
        auditEntry.put("failing_check", failingCheck);
        auditEntry.put("pre_state_hash", preStateHash);
        auditEntry.put("post_state_hash", postStateHash);
        auditEntry.put("containment_action", "THREAD_FROZEN");
        auditEntry.put("covenant_principle_violated", getPrincipleViolated(type));
        
        String filename = errorId + ".json";
        Path auditFile = AUDIT_DIR.resolve(filename);
        
        try (FileWriter writer = new FileWriter(auditFile.toFile())) {
            GSON.toJson(auditEntry, writer);
            String auditHash = hashFile(auditFile);
            System.out.println("[AUDIT] Error logged: " + errorId + " | Hash: " + auditHash);
        } catch (IOException e) {
            System.err.println("Failed to write audit log: " + e.getMessage());
        }
        
        return errorId;
    }
    
    private static String generateErrorId(ErrorType type) {
        String prefix = type.name().substring(0, 3);
        long timestamp = System.currentTimeMillis();
        return prefix + "_" + timestamp;
    }
    
    private static String getPrincipleViolated(ErrorType type) {
        return switch (type) {
            case BIJECTIVE_VIOLATION -> "LOGOS (Truth-Only)";
            case MERKLE_MISMATCH -> "LOGOS (Cryptographic Verification)";
            case CAUSALITY_LOOP -> "CHALCEDON (Divine Order)";
            case DEBUGGER_ALERT -> "KENOSIS (Self-Emptying Diagnostics)";
        };
    }
    
    private static String hashFile(Path file) {
        try {
            byte[] fileBytes = Files.readAllBytes(file);
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(fileBytes);
            
            StringBuilder hexString = new StringBuilder();
            for (byte b : hashBytes) {
                hexString.append(String.format("%02X", b));
            }
            return hexString.toString();
        } catch (IOException | NoSuchAlgorithmException e) {
            return "HASH_FAILED";
        }
    }
    
    /**
     * Check if an audit log exists for the given operation ID.
     * Used by CovenantVerifier.verifyTransparentOperation()
     */
    public static boolean auditExists(String operationId) {
        Path auditFile = AUDIT_DIR.resolve(operationId + ".json");
        return Files.exists(auditFile);
    }
}
