/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: Archived worlds transition after grace period; no indefinite spectator limbo
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.spectator;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Manages the countdown before an archived world is flagged for archival.
 *
 * <p>When a player dies in Hardcore mode, a countdown is started equal to
 * {@link HikConfig#SPECTATOR_GRACE_MINUTES} minutes. When the countdown
 * expires, {@link #checkAndArchive} logs the archive-pending marker.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class ArchiveCountdown {

    private static final Map<String, Long> countdownEndTimes = new HashMap<>();
    private static final int ARCHIVE_CHECK_INTERVAL_TICKS = 100;
    /** Maps player UUID -> world name so archive logging stays tied to the correct world. */
    private static final Map<String, String> countdownWorldNames = new HashMap<>();
    private static int tickCounter = 0;

    private ArchiveCountdown() {}

    // ---- Countdown management ---------------------------------------------------

    /**
     * Records the expiry time for the given player UUID.
     * Overwrites any existing countdown.
     */
    public static void startCountdown(String uuid) {
        startCountdown(uuid, "unknown");
    }

    /**
     * Records the expiry time for the given player UUID, associating it with a world name.
     * Overwrites any existing countdown.
     */
    public static void startCountdown(String uuid, String worldName) {
        long endTime = System.currentTimeMillis()
                + (long) HikConfig.SPECTATOR_GRACE_MINUTES.get() * 60_000L;
        countdownEndTimes.put(uuid, endTime);
        countdownWorldNames.put(uuid, worldName);
    }

    /**
     * Returns {@code true} if a countdown exists for this UUID and has expired.
     */
    public static boolean isExpired(String uuid) {
        Long endTime = countdownEndTimes.get(uuid);
        if (endTime == null) return false;
        return System.currentTimeMillis() > endTime;
    }

    /**
     * Returns the remaining time in seconds, or {@code 0} if expired or not started.
     */
    public static long getRemainingSeconds(String uuid) {
        Long endTime = countdownEndTimes.get(uuid);
        if (endTime == null) return 0;
        long remaining = endTime - System.currentTimeMillis();
        return remaining > 0 ? remaining / 1000 : 0;
    }

    /**
     * If the countdown has expired, logs an "archive pending" notice and removes
     * the entry from the countdown map.
     */
    public static void checkAndArchive(String uuid, String worldName) {
        if (!isExpired(uuid)) return;
        countdownEndTimes.remove(uuid);
        countdownWorldNames.remove(uuid);
        System.out.println("[HIK] ARCHIVE PENDING: player=" + uuid
                + " world=" + worldName
                + " archive_path=" + HikConfig.ARCHIVE_PATH.get());
    }

    // ---- Event handler ----------------------------------------------------------

    @SubscribeEvent
    public static void onServerTick(TickEvent.ServerTickEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (event.phase != TickEvent.Phase.END) return;
        tickCounter++;
        if (tickCounter < ARCHIVE_CHECK_INTERVAL_TICKS) return;
        tickCounter = 0;

        // Iterate over a snapshot to avoid ConcurrentModificationException
        for (String uuid : List.copyOf(countdownEndTimes.keySet())) {
            if (isExpired(uuid)) {
                String worldName = countdownWorldNames.getOrDefault(uuid, "unknown");
                checkAndArchive(uuid, worldName);
            }
        }
    }
}
