/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: Locked players may not escape the death seal via commands
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.spectator;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.event.CommandEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.List;

/**
 * Intercepts commands for players under a spectator death-seal lock.
 *
 * <p>The following commands are blocked for locked players:
 * {@code gamemode}, {@code gm}, {@code give}, {@code tp}, {@code teleport},
 * {@code kill}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class CommandInterceptor {

    private static final List<String> BLOCKED_COMMANDS =
            List.of("gamemode", "gm", "give", "tp", "teleport", "kill");

    private CommandInterceptor() {}

    @SubscribeEvent
    public static void onCommand(CommandEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;

        var source = event.getParseResults().getContext().getSource();
        if (!(source.getEntity() instanceof ServerPlayer player)) return;
        if (!player.level().getLevelData().isHardcore()) return;
        if (!SpectatorLockHandler.isLocked(player.getStringUUID())) return;

        String input = event.getParseResults().getReader().getString().toLowerCase();
        for (String blocked : BLOCKED_COMMANDS) {
            if (input.startsWith("/" + blocked) || input.startsWith(blocked)) {
                event.setCanceled(true);
                player.displayClientMessage(
                        Component.literal("[HIK] Command blocked: death seal is active."), false);
                return;
            }
        }
    }
}
