/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: Locked players may not escape the death seal via commands
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.spectator;

import com.truthsystems.TruthSystems;
import com.truthsystems.audit.CovenantVerifier;
import com.truthsystems.audit.ErrorLogger;
import com.truthsystems.hardcore.HikConfig;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraftforge.event.CommandEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.List;

/**
 * Intercepts commands for players under a spectator death-seal lock.
 *
 * <p>The following commands are blocked for locked players:
 * {@code gamemode}, {@code gm}, {@code give}, {@code tp}, {@code teleport},
 * {@code kill}.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class CommandInterceptor {

    private static final List<String> BLOCKED_COMMANDS =
            List.of("gamemode", "gm", "give", "tp", "teleport", "kill");

    private CommandInterceptor() {}

    public static boolean isBlockedCommand(String input) {
        String normalized = input.toLowerCase();
        String command = normalized.startsWith("/") ? normalized.substring(1) : normalized;
        int spaceIdx = command.indexOf(' ');
        String commandName = spaceIdx >= 0 ? command.substring(0, spaceIdx) : command;
        return BLOCKED_COMMANDS.contains(commandName);
    }

    @SubscribeEvent
    public static void onCommand(CommandEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;

        var source = event.getParseResults().getContext().getSource();
        if (!(source.getEntity() instanceof ServerPlayer player)) return;
        if (!player.level().getLevelData().isHardcore()) return;
        if (!SpectatorLockHandler.isLocked(player.getStringUUID())) return;

        String input = event.getParseResults().getReader().getString();
        if (isBlockedCommand(input)) {
            if (!CovenantVerifier.verifySpectatorLock(player)) {
                ErrorLogger.logError(
                        ErrorLogger.ErrorType.SPECTATOR_VIOLATION,
                        TruthSystems.MODID,
                        "spectator_lock_verification_failed",
                        "",
                        "");
            }
            event.setCanceled(true);
            player.displayClientMessage(
                    Component.literal("[HIK] Command blocked: death seal is active."), false);
        }
    }
}
