/*
 * COVENANT: Σ_LORA_COVENANT v1.0
 * SYSTEM: Hardcore Integrity Keeper (HIK)
 * PRINCIPLE: CHALCEDON (Divine Order)
 * CONSTRAINT: Dead players must remain in spectator; the lock is non-negotiable
 * FILE_HASH: [SHA256_AUTOGENERATED]
 */
package com.truthsystems.hardcore.spectator;

import com.truthsystems.TruthSystems;
import com.truthsystems.hardcore.HikConfig;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.GameType;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Enforces spectator mode for players whose death has been sealed by HIK.
 *
 * <p>A per-tick enforcement is applied so that any attempt to change game mode
 * (e.g., via mods or commands that bypass the command interceptor) is reverted.
 */
@Mod.EventBusSubscriber(modid = TruthSystems.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
public class SpectatorLockHandler {

    private static final Set<String> lockedPlayers =
            Collections.synchronizedSet(new HashSet<>());

    private SpectatorLockHandler() {}

    // ---- Lock management --------------------------------------------------------

    /** Adds the player UUID to the spectator lock set. */
    public static void lockPlayer(String uuid) {
        lockedPlayers.add(uuid);
    }

    /** Removes the player UUID from the spectator lock set. */
    public static void unlockPlayer(String uuid) {
        lockedPlayers.remove(uuid);
    }

    /** Returns {@code true} if the UUID is in the spectator lock set. */
    public static boolean isLocked(String uuid) {
        return lockedPlayers.contains(uuid);
    }

    /**
     * Sets the player to {@link GameType#SPECTATOR} if they are in the lock set
     * and currently not already in spectator mode.
     */
    public static void enforceSpectator(ServerPlayer player) {
        if (isLocked(player.getStringUUID())
                && player.gameMode.getGameModeForPlayer() != GameType.SPECTATOR) {
            player.setGameMode(GameType.SPECTATOR);
        }
    }

    // ---- Event handler ----------------------------------------------------------

    @SubscribeEvent
    public static void onPlayerTick(TickEvent.PlayerTickEvent event) {
        if (!HikConfig.ENABLE_HIK.get()) return;
        if (event.phase != TickEvent.Phase.END) return;
        if (!(event.player instanceof ServerPlayer player)) return;
        if (!player.level().getLevelData().isHardcore()) return;
        if (isLocked(player.getStringUUID())) {
            enforceSpectator(player);
        }
    }
}
